CREATE TABLE LOCK_TABLE (
  CODE VARCHAR(128) NOT NULL IDENTITY
);

INSERT INTO LOCK_TABLE VALUES ('PESSIMISTIC_LOCK');

CREATE TABLE TABLE_ALPHA (
  ID    INTEGER NOT NULL IDENTITY,
  VALUE VARCHAR(256)
);
